import type { AsmaulHusna } from "./types";

/**
 * The 99 Names of Allah (Asmaul Husna), based on the well-known
 * Tirmidhi enumeration. Each name: Arabic, transliteration, and a
 * concise bilingual meaning suitable for children.
 *
 * EDITORIAL NOTE: Verify Arabic forms + meanings with a qualified
 * scholar before any "verified" claim.
 */
export const asmaulHusnaList: AsmaulHusna[] = [
  { number: 1, arabic: "الرَّحْمَٰنُ", transliteration: "Ar-Rahmaan", meaning: { id: "Maha Pengasih", en: "The Most Compassionate" } },
  { number: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahiim", meaning: { id: "Maha Penyayang", en: "The Most Merciful" } },
  { number: 3, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: { id: "Maha Merajai", en: "The King" } },
  { number: 4, arabic: "الْقُدُّوسُ", transliteration: "Al-Qudduus", meaning: { id: "Maha Suci", en: "The Most Holy" } },
  { number: 5, arabic: "السَّلَامُ", transliteration: "As-Salaam", meaning: { id: "Maha Pemberi Kesejahteraan", en: "The Source of Peace" } },
  { number: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: { id: "Maha Pemberi Keamanan", en: "The Granter of Security" } },
  { number: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaimin", meaning: { id: "Maha Memelihara", en: "The Guardian" } },
  { number: 8, arabic: "الْعَزِيزُ", transliteration: "Al-'Aziiz", meaning: { id: "Maha Perkasa", en: "The Almighty" } },
  { number: 9, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbaar", meaning: { id: "Maha Kuasa", en: "The Compeller" } },
  { number: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: { id: "Maha Megah", en: "The Supreme" } },
  { number: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaaliq", meaning: { id: "Maha Pencipta", en: "The Creator" } },
  { number: 12, arabic: "الْبَارِئُ", transliteration: "Al-Baari'", meaning: { id: "Maha Mengadakan", en: "The Originator" } },
  { number: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Mushawwir", meaning: { id: "Maha Membentuk Rupa", en: "The Fashioner" } },
  { number: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffaar", meaning: { id: "Maha Pengampun", en: "The Ever-Forgiving" } },
  { number: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhaar", meaning: { id: "Maha Memaksa", en: "The Subduer" } },
  { number: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhaab", meaning: { id: "Maha Pemberi Karunia", en: "The Bestower" } },
  { number: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaaq", meaning: { id: "Maha Pemberi Rezeki", en: "The Provider" } },
  { number: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattaah", meaning: { id: "Maha Pembuka Rahmat", en: "The Opener" } },
  { number: 19, arabic: "الْعَلِيمُ", transliteration: "Al-'Aliim", meaning: { id: "Maha Mengetahui", en: "The All-Knowing" } },
  { number: 20, arabic: "الْقَابِضُ", transliteration: "Al-Qaabidh", meaning: { id: "Maha Menyempitkan", en: "The Withholder" } },
  { number: 21, arabic: "الْبَاسِطُ", transliteration: "Al-Baasith", meaning: { id: "Maha Melapangkan", en: "The Expander" } },
  { number: 22, arabic: "الْخَافِضُ", transliteration: "Al-Khaafidh", meaning: { id: "Maha Merendahkan", en: "The Abaser" } },
  { number: 23, arabic: "الرَّافِعُ", transliteration: "Ar-Raafi'", meaning: { id: "Maha Meninggikan", en: "The Exalter" } },
  { number: 24, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: { id: "Maha Memuliakan", en: "The Honourer" } },
  { number: 25, arabic: "الْمُذِلُّ", transliteration: "Al-Mudzill", meaning: { id: "Maha Menghinakan", en: "The Humiliator" } },
  { number: 26, arabic: "السَّمِيعُ", transliteration: "As-Samii'", meaning: { id: "Maha Mendengar", en: "The All-Hearing" } },
  { number: 27, arabic: "الْبَصِيرُ", transliteration: "Al-Bashiir", meaning: { id: "Maha Melihat", en: "The All-Seeing" } },
  { number: 28, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: { id: "Maha Menetapkan", en: "The Judge" } },
  { number: 29, arabic: "الْعَدْلُ", transliteration: "Al-'Adl", meaning: { id: "Maha Adil", en: "The Utterly Just" } },
  { number: 30, arabic: "اللَّطِيفُ", transliteration: "Al-Lathiif", meaning: { id: "Maha Lembut", en: "The Subtle One" } },
  { number: 31, arabic: "الْخَبِيرُ", transliteration: "Al-Khabiir", meaning: { id: "Maha Mengetahui Rahasia", en: "The All-Aware" } },
  { number: 32, arabic: "الْحَلِيمُ", transliteration: "Al-Haliim", meaning: { id: "Maha Penyantun", en: "The Forbearing" } },
  { number: 33, arabic: "الْعَظِيمُ", transliteration: "Al-'Azhiim", meaning: { id: "Maha Agung", en: "The Magnificent" } },
  { number: 34, arabic: "الْغَفُورُ", transliteration: "Al-Ghafuur", meaning: { id: "Maha Pengampun", en: "The All-Forgiving" } },
  { number: 35, arabic: "الشَّكُورُ", transliteration: "Asy-Syakuur", meaning: { id: "Maha Pembalas Budi", en: "The Most Appreciative" } },
  { number: 36, arabic: "الْعَلِيُّ", transliteration: "Al-'Aliyy", meaning: { id: "Maha Tinggi", en: "The Most High" } },
  { number: 37, arabic: "الْكَبِيرُ", transliteration: "Al-Kabiir", meaning: { id: "Maha Besar", en: "The Most Great" } },
  { number: 38, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiizh", meaning: { id: "Maha Menjaga", en: "The Preserver" } },
  { number: 39, arabic: "الْمُقِيتُ", transliteration: "Al-Muqiit", meaning: { id: "Maha Pemberi Kecukupan", en: "The Sustainer" } },
  { number: 40, arabic: "الْحَسِيبُ", transliteration: "Al-Hasiib", meaning: { id: "Maha Membuat Perhitungan", en: "The Reckoner" } },
  { number: 41, arabic: "الْجَلِيلُ", transliteration: "Al-Jaliil", meaning: { id: "Maha Luhur", en: "The Majestic" } },
  { number: 42, arabic: "الْكَرِيمُ", transliteration: "Al-Kariim", meaning: { id: "Maha Pemurah", en: "The Most Generous" } },
  { number: 43, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqiib", meaning: { id: "Maha Mengawasi", en: "The Watchful" } },
  { number: 44, arabic: "الْمُجِيبُ", transliteration: "Al-Mujiib", meaning: { id: "Maha Mengabulkan", en: "The Responsive" } },
  { number: 45, arabic: "الْوَاسِعُ", transliteration: "Al-Waasi'", meaning: { id: "Maha Luas", en: "The All-Encompassing" } },
  { number: 46, arabic: "الْحَكِيمُ", transliteration: "Al-Hakiim", meaning: { id: "Maha Bijaksana", en: "The All-Wise" } },
  { number: 47, arabic: "الْوَدُودُ", transliteration: "Al-Waduud", meaning: { id: "Maha Mengasihi", en: "The Most Loving" } },
  { number: 48, arabic: "الْمَجِيدُ", transliteration: "Al-Majiid", meaning: { id: "Maha Mulia", en: "The Most Glorious" } },
  { number: 49, arabic: "الْبَاعِثُ", transliteration: "Al-Baa'its", meaning: { id: "Maha Membangkitkan", en: "The Resurrector" } },
  { number: 50, arabic: "الشَّهِيدُ", transliteration: "Asy-Syahiid", meaning: { id: "Maha Menyaksikan", en: "The Witness" } },
  { number: 51, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: { id: "Maha Benar", en: "The Absolute Truth" } },
  { number: 52, arabic: "الْوَكِيلُ", transliteration: "Al-Wakiil", meaning: { id: "Maha Pemelihara", en: "The Trustee" } },
  { number: 53, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: { id: "Maha Kuat", en: "The All-Strong" } },
  { number: 54, arabic: "الْمَتِينُ", transliteration: "Al-Matiin", meaning: { id: "Maha Kokoh", en: "The Firm" } },
  { number: 55, arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: { id: "Maha Melindungi", en: "The Protecting Friend" } },
  { number: 56, arabic: "الْحَمِيدُ", transliteration: "Al-Hamiid", meaning: { id: "Maha Terpuji", en: "The All-Praiseworthy" } },
  { number: 57, arabic: "الْمُحْصِي", transliteration: "Al-Muhshii", meaning: { id: "Maha Menghitung", en: "The Accounter" } },
  { number: 58, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi'", meaning: { id: "Maha Memulai", en: "The Originator" } },
  { number: 59, arabic: "الْمُعِيدُ", transliteration: "Al-Mu'iid", meaning: { id: "Maha Mengembalikan", en: "The Restorer" } },
  { number: 60, arabic: "الْمُحْيِي", transliteration: "Al-Muhyii", meaning: { id: "Maha Menghidupkan", en: "The Giver of Life" } },
  { number: 61, arabic: "الْمُمِيتُ", transliteration: "Al-Mumiit", meaning: { id: "Maha Mematikan", en: "The Bringer of Death" } },
  { number: 62, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: { id: "Maha Hidup", en: "The Ever-Living" } },
  { number: 63, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyuum", meaning: { id: "Maha Mandiri", en: "The Self-Subsisting" } },
  { number: 64, arabic: "الْوَاجِدُ", transliteration: "Al-Waajid", meaning: { id: "Maha Menemukan", en: "The Perceiver" } },
  { number: 65, arabic: "الْمَاجِدُ", transliteration: "Al-Maajid", meaning: { id: "Maha Mulia", en: "The Illustrious" } },
  { number: 66, arabic: "الْوَاحِدُ", transliteration: "Al-Waahid", meaning: { id: "Maha Esa", en: "The One" } },
  { number: 67, arabic: "الْأَحَدُ", transliteration: "Al-Ahad", meaning: { id: "Maha Tunggal", en: "The Indivisible" } },
  { number: 68, arabic: "الصَّمَدُ", transliteration: "As-Shamad", meaning: { id: "Maha Tempat Bergantung", en: "The Eternal Refuge" } },
  { number: 69, arabic: "الْقَادِرُ", transliteration: "Al-Qaadir", meaning: { id: "Maha Kuasa", en: "The All-Powerful" } },
  { number: 70, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: { id: "Maha Berkuasa", en: "The Determiner" } },
  { number: 71, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: { id: "Maha Mendahulukan", en: "The Expediter" } },
  { number: 72, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: { id: "Maha Mengakhirkan", en: "The Delayer" } },
  { number: 73, arabic: "الْأَوَّلُ", transliteration: "Al-Awwal", meaning: { id: "Maha Awal", en: "The First" } },
  { number: 74, arabic: "الْآخِرُ", transliteration: "Al-Aakhir", meaning: { id: "Maha Akhir", en: "The Last" } },
  { number: 75, arabic: "الظَّاهِرُ", transliteration: "Azh-Zhaahir", meaning: { id: "Maha Nyata", en: "The Manifest" } },
  { number: 76, arabic: "الْبَاطِنُ", transliteration: "Al-Baathin", meaning: { id: "Maha Tersembunyi", en: "The Hidden" } },
  { number: 77, arabic: "الْوَالِي", transliteration: "Al-Waalii", meaning: { id: "Maha Menguasai", en: "The Governor" } },
  { number: 78, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'aalii", meaning: { id: "Maha Tinggi", en: "The Most Exalted" } },
  { number: 79, arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: { id: "Maha Penderma", en: "The Source of Goodness" } },
  { number: 80, arabic: "التَّوَّابُ", transliteration: "At-Tawwaab", meaning: { id: "Maha Penerima Tobat", en: "The Acceptor of Repentance" } },
  { number: 81, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: { id: "Maha Pemberi Balasan", en: "The Avenger" } },
  { number: 82, arabic: "الْعَفُوُّ", transliteration: "Al-'Afuww", meaning: { id: "Maha Pemaaf", en: "The Pardoner" } },
  { number: 83, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uuf", meaning: { id: "Maha Pengasih", en: "The Most Kind" } },
  { number: 84, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Maalikul-Mulk", meaning: { id: "Maha Penguasa Kerajaan", en: "Master of the Kingdom" } },
  { number: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dzul-Jalaali wal-Ikraam", meaning: { id: "Maha Pemilik Keagungan dan Kemuliaan", en: "Lord of Majesty and Honour" } },
  { number: 86, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsith", meaning: { id: "Maha Adil", en: "The Equitable" } },
  { number: 87, arabic: "الْجَامِعُ", transliteration: "Al-Jaami'", meaning: { id: "Maha Mengumpulkan", en: "The Gatherer" } },
  { number: 88, arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: { id: "Maha Kaya", en: "The Self-Sufficient" } },
  { number: 89, arabic: "الْمُغْنِي", transliteration: "Al-Mughnii", meaning: { id: "Maha Pemberi Kekayaan", en: "The Enricher" } },
  { number: 90, arabic: "الْمَانِعُ", transliteration: "Al-Maani'", meaning: { id: "Maha Mencegah", en: "The Preventer" } },
  { number: 91, arabic: "الضَّارُّ", transliteration: "Adh-Dhaarr", meaning: { id: "Maha Pemberi Bahaya", en: "The Distresser" } },
  { number: 92, arabic: "النَّافِعُ", transliteration: "An-Naafi'", meaning: { id: "Maha Pemberi Manfaat", en: "The Benefactor" } },
  { number: 93, arabic: "النُّورُ", transliteration: "An-Nuur", meaning: { id: "Maha Bercahaya", en: "The Light" } },
  { number: 94, arabic: "الْهَادِي", transliteration: "Al-Haadii", meaning: { id: "Maha Pemberi Petunjuk", en: "The Guide" } },
  { number: 95, arabic: "الْبَدِيعُ", transliteration: "Al-Badii'", meaning: { id: "Maha Pencipta Tiada Bandingan", en: "The Incomparable Originator" } },
  { number: 96, arabic: "الْبَاقِي", transliteration: "Al-Baaqii", meaning: { id: "Maha Kekal", en: "The Everlasting" } },
  { number: 97, arabic: "الْوَارِثُ", transliteration: "Al-Waarits", meaning: { id: "Maha Pewaris", en: "The Inheritor" } },
  { number: 98, arabic: "الرَّشِيدُ", transliteration: "Ar-Rasyiid", meaning: { id: "Maha Pembimbing", en: "The Guide to the Right Path" } },
  { number: 99, arabic: "الصَّبُورُ", transliteration: "As-Shabuur", meaning: { id: "Maha Sabar", en: "The Patient One" } },
];

export function getAllAsmaulHusna(): AsmaulHusna[] {
  return asmaulHusnaList;
}
