import type { AsmaulHusna } from "./types";

/**
 * The 99 Names of Allah (Asmaul Husna), based on the well-known
 * Tirmidhi enumeration. Each name: Arabic, transliteration, a concise
 * bilingual meaning, a warm kid-friendly reflection, and a concrete way
 * to share the name with a child.
 *
 * EDITORIAL NOTE: Verify Arabic forms + meanings with a qualified
 * scholar before any "verified" claim.
 */
export const asmaulHusnaList: AsmaulHusna[] = [
  {
    number: 1,
    slug: "ar-rahman",
    arabic: "الرَّحْمَٰنُ",
    transliteration: "Ar-Rahmaan",
    meaning: { id: "Maha Pengasih", en: "The Most Compassionate" },
    explanation: { id: "Allah menyayangi semua makhluk-Nya, yang baik maupun yang nakal, di dunia ini. Kasih sayang-Nya lebih luas daripada langit dan bumi.", en: "Allah is kind to every creature in this world — the good and the naughty alike. His compassion is wider than the sky and the earth." },
    forKids: { id: "Tunjukkan ke anak: matahari yang hangat dan hujan yang menyuburkan adalah tanda Ar-Rahman menyayangi semua orang.", en: "Show your child: the warm sun and the nourishing rain are signs that Ar-Rahman cares for everyone." },
  },
  {
    number: 2,
    slug: "ar-rahim",
    arabic: "الرَّحِيمُ",
    transliteration: "Ar-Rahiim",
    meaning: { id: "Maha Penyayang", en: "The Most Merciful" },
    explanation: { id: "Allah memberi kasih sayang yang istimewa kepada orang yang beriman dan berbuat baik. Sayang-Nya tak pernah habis.", en: "Allah gives a special, lasting mercy to those who believe and do good. His love never runs out." },
    forKids: { id: "Bisikkan: setiap kali kita berbuat baik, Ar-Rahim semakin sayang pada kita.", en: "Whisper: every time we do something good, Ar-Rahim loves us even more." },
  },
  {
    number: 3,
    slug: "al-malik",
    arabic: "الْمَلِكُ",
    transliteration: "Al-Malik",
    meaning: { id: "Maha Merajai", en: "The King" },
    explanation: { id: "Allah adalah Raja dari segala raja. Seluruh langit, bumi, dan semua isinya adalah milik-Nya.", en: "Allah is the King of all kings. The heavens, the earth, and everything in them belong to Him." },
    forKids: { id: "Tanya anak: siapa raja terbesar yang memiliki bintang, laut, dan seluruh dunia? Allah, Al-Malik.", en: "Ask your child: who is the greatest King who owns the stars, the seas, and the whole world? Allah, Al-Malik." },
  },
  {
    number: 4,
    slug: "al-quddus",
    arabic: "الْقُدُّوسُ",
    transliteration: "Al-Qudduus",
    meaning: { id: "Maha Suci", en: "The Most Holy" },
    explanation: { id: "Allah Maha Suci, bersih dari segala kekurangan dan kesalahan. Tidak ada yang seperti Dia.", en: "Allah is the Most Holy, free of any flaw or mistake. Nothing is like Him." },
    forKids: { id: "Ajak anak mengucap 'Subhanallah' — artinya Allah Maha Suci dan sempurna.", en: "Teach your child to say 'Subhanallah' — it means Allah is pure and perfect." },
  },
  {
    number: 5,
    slug: "as-salam",
    arabic: "السَّلَامُ",
    transliteration: "As-Salaam",
    meaning: { id: "Maha Pemberi Kesejahteraan", en: "The Source of Peace" },
    explanation: { id: "Allah adalah sumber kedamaian. Dari-Nya datang rasa tenang dan selamat di hati kita.", en: "Allah is the source of peace. From Him comes the calm and safety in our hearts." },
    forKids: { id: "Saat anak takut, ingatkan bahwa As-Salam bisa membuat hati tenang kembali.", en: "When your child is scared, remind them that As-Salam can make the heart calm again." },
  },
  {
    number: 6,
    slug: "al-mumin",
    arabic: "الْمُؤْمِنُ",
    transliteration: "Al-Mu'min",
    meaning: { id: "Maha Pemberi Keamanan", en: "The Granter of Security" },
    explanation: { id: "Allah memberi rasa aman kepada hamba-Nya. Dia menjaga kita dari rasa takut.", en: "Allah grants security to His servants. He shelters us from fear." },
    forKids: { id: "Sebelum tidur, katakan: Al-Mu'min menjaga kita sepanjang malam.", en: "Before sleep, say: Al-Mu'min keeps us safe all night long." },
  },
  {
    number: 7,
    slug: "al-muhaimin",
    arabic: "الْمُهَيْمِنُ",
    transliteration: "Al-Muhaimin",
    meaning: { id: "Maha Memelihara", en: "The Guardian" },
    explanation: { id: "Allah melihat dan memelihara segala sesuatu. Tidak ada yang luput dari penjagaan-Nya.", en: "Allah watches over and protects all things. Nothing escapes His care." },
    forKids: { id: "Ingatkan anak: di mana pun kita berada, Al-Muhaimin selalu menjaga.", en: "Remind your child: wherever we are, Al-Muhaimin is always watching over us." },
  },
  {
    number: 8,
    slug: "al-aziz",
    arabic: "الْعَزِيزُ",
    transliteration: "Al-'Aziiz",
    meaning: { id: "Maha Perkasa", en: "The Almighty" },
    explanation: { id: "Allah Maha Perkasa, tidak ada yang bisa mengalahkan-Nya. Kekuatan-Nya tak tertandingi.", en: "Allah is the Almighty; no one can overcome Him. His might has no equal." },
    forKids: { id: "Ceritakan bahwa kekuatan apa pun di dunia kecil di hadapan Al-'Aziz.", en: "Tell your child that any power in the world is small before Al-'Aziz." },
  },
  {
    number: 9,
    slug: "al-jabbar",
    arabic: "الْجَبَّارُ",
    transliteration: "Al-Jabbaar",
    meaning: { id: "Maha Kuasa", en: "The Compeller" },
    explanation: { id: "Allah Maha Kuasa yang memperbaiki segala yang rusak dan menguatkan yang lemah.", en: "Allah is the Compeller, who mends what is broken and strengthens the weak." },
    forKids: { id: "Saat anak sedih atau jatuh, katakan Al-Jabbar bisa membuat segalanya baik kembali.", en: "When your child is hurt or sad, say Al-Jabbar can make things whole again." },
  },
  {
    number: 10,
    slug: "al-mutakabbir",
    arabic: "الْمُتَكَبِّرُ",
    transliteration: "Al-Mutakabbir",
    meaning: { id: "Maha Megah", en: "The Supreme" },
    explanation: { id: "Hanya Allah yang berhak memiliki keagungan dan kebesaran tertinggi. Tidak ada yang sombong di hadapan-Nya.", en: "Only Allah deserves the highest greatness and majesty. No one is proud before Him." },
    forKids: { id: "Ajarkan rendah hati: kita kecil, hanya Al-Mutakabbir yang benar-benar besar.", en: "Teach humility: we are small; only Al-Mutakabbir is truly great." },
  },
  {
    number: 11,
    slug: "al-khaliq",
    arabic: "الْخَالِقُ",
    transliteration: "Al-Khaaliq",
    meaning: { id: "Maha Pencipta", en: "The Creator" },
    explanation: { id: "Allah menciptakan segala sesuatu dari tidak ada menjadi ada — langit, hewan, dan diri kita.", en: "Allah creates everything from nothing — the sky, the animals, and us." },
    forKids: { id: "Tunjuk seekor kupu-kupu: siapa yang membuatnya begitu indah? Al-Khaliq.", en: "Point to a butterfly: who made it so beautiful? Al-Khaliq." },
  },
  {
    number: 12,
    slug: "al-bari",
    arabic: "الْبَارِئُ",
    transliteration: "Al-Baari'",
    meaning: { id: "Maha Mengadakan", en: "The Originator" },
    explanation: { id: "Allah membentuk setiap makhluk dengan rapi dan serasi, tanpa ada yang cacat.", en: "Allah shapes every creature in perfect harmony, with nothing out of place." },
    forKids: { id: "Lihat jari-jari mungil anak: Al-Bari' menyusunnya dengan sempurna.", en: "Look at your child's tiny fingers: Al-Bari' arranged them perfectly." },
  },
  {
    number: 13,
    slug: "al-mushawwir",
    arabic: "الْمُصَوِّرُ",
    transliteration: "Al-Mushawwir",
    meaning: { id: "Maha Membentuk Rupa", en: "The Fashioner" },
    explanation: { id: "Allah memberi rupa dan bentuk yang berbeda-beda pada setiap makhluk. Tak ada dua yang persis sama.", en: "Allah gives each creature its own unique form. No two are exactly alike." },
    forKids: { id: "Bandingkan wajah anggota keluarga: Al-Mushawwir membuat setiap orang istimewa.", en: "Compare your family's faces: Al-Mushawwir made each person special." },
  },
  {
    number: 14,
    slug: "al-ghaffar",
    arabic: "الْغَفَّارُ",
    transliteration: "Al-Ghaffaar",
    meaning: { id: "Maha Pengampun", en: "The Ever-Forgiving" },
    explanation: { id: "Allah Maha Pengampun. Berapa kali pun kita salah lalu bertobat, Dia mengampuni.", en: "Allah is the Ever-Forgiving. However often we slip and turn back to Him, He forgives." },
    forKids: { id: "Ajari anak berkata 'Astaghfirullah' ketika berbuat salah — Al-Ghaffar pasti memaafkan.", en: "Teach your child to say 'Astaghfirullah' after a mistake — Al-Ghaffar always forgives." },
  },
  {
    number: 15,
    slug: "al-qahhar",
    arabic: "الْقَهَّارُ",
    transliteration: "Al-Qahhaar",
    meaning: { id: "Maha Memaksa", en: "The Subduer" },
    explanation: { id: "Allah berkuasa penuh atas segala sesuatu. Semua tunduk pada kehendak-Nya.", en: "Allah has complete power over all things. Everything yields to His will." },
    forKids: { id: "Jelaskan bahwa siang berganti malam karena perintah Al-Qahhar.", en: "Explain that day turns to night by the command of Al-Qahhar." },
  },
  {
    number: 16,
    slug: "al-wahhab",
    arabic: "الْوَهَّابُ",
    transliteration: "Al-Wahhaab",
    meaning: { id: "Maha Pemberi Karunia", en: "The Bestower" },
    explanation: { id: "Allah memberi tanpa diminta dan tanpa mengharap balasan. Pemberian-Nya tak terhitung.", en: "Allah gives without being asked and without expecting anything back. His gifts are countless." },
    forKids: { id: "Hitung bersama nikmat hari ini: udara, makanan, keluarga — semua dari Al-Wahhab.", en: "Count today's blessings together: air, food, family — all from Al-Wahhab." },
  },
  {
    number: 17,
    slug: "ar-razzaq",
    arabic: "الرَّزَّاقُ",
    transliteration: "Ar-Razzaaq",
    meaning: { id: "Maha Pemberi Rezeki", en: "The Provider" },
    explanation: { id: "Allah memberi rezeki kepada setiap makhluk, dari manusia sampai semut terkecil.", en: "Allah provides for every creature, from people to the smallest ant." },
    forKids: { id: "Saat makan, ingatkan: Ar-Razzaq yang memberi kita makanan ini.", en: "At mealtime, remind your child: Ar-Razzaq gave us this food." },
  },
  {
    number: 18,
    slug: "al-fattah",
    arabic: "الْفَتَّاحُ",
    transliteration: "Al-Fattaah",
    meaning: { id: "Maha Pembuka Rahmat", en: "The Opener" },
    explanation: { id: "Allah membuka pintu rahmat, jalan keluar, dan kebaikan yang tertutup bagi kita.", en: "Allah opens the doors of mercy, solutions, and good that seem closed to us." },
    forKids: { id: "Saat anak kesulitan, ajak berdoa agar Al-Fattah membukakan jalan.", en: "When your child struggles, pray together that Al-Fattah opens a way." },
  },
  {
    number: 19,
    slug: "al-alim",
    arabic: "الْعَلِيمُ",
    transliteration: "Al-'Aliim",
    meaning: { id: "Maha Mengetahui", en: "The All-Knowing" },
    explanation: { id: "Allah mengetahui segala sesuatu — yang tampak maupun yang tersembunyi, bahkan isi hati kita.", en: "Allah knows everything — the seen and the hidden, even what is in our hearts." },
    forKids: { id: "Ingatkan dengan lembut: Al-'Alim tahu niat baik kita, jadi mari selalu jujur.", en: "Gently remind: Al-'Alim knows our good intentions, so let's always be honest." },
  },
  {
    number: 20,
    slug: "al-qabidh",
    arabic: "الْقَابِضُ",
    transliteration: "Al-Qaabidh",
    meaning: { id: "Maha Menyempitkan", en: "The Withholder" },
    explanation: { id: "Allah menahan dan menyempitkan sesuai hikmah-Nya. Apa yang ditahan-Nya pasti ada kebaikannya.", en: "Allah withholds by His wisdom. Whatever He holds back carries a hidden good." },
    forKids: { id: "Ajarkan sabar: kadang Al-Qabidh menahan sesuatu karena ada yang lebih baik menanti.", en: "Teach patience: sometimes Al-Qabidh holds something back because better is coming." },
  },
  {
    number: 21,
    slug: "al-basith",
    arabic: "الْبَاسِطُ",
    transliteration: "Al-Baasith",
    meaning: { id: "Maha Melapangkan", en: "The Expander" },
    explanation: { id: "Allah melapangkan rezeki, hati, dan kebahagiaan bagi siapa yang Dia kehendaki.", en: "Allah expands provision, hearts, and joy for whom He wills." },
    forKids: { id: "Saat hati senang dan lega, katakan: ini lapang dari Al-Basith.", en: "When the heart feels light and happy, say: this ease is from Al-Basith." },
  },
  {
    number: 22,
    slug: "al-khafidh",
    arabic: "الْخَافِضُ",
    transliteration: "Al-Khaafidh",
    meaning: { id: "Maha Merendahkan", en: "The Abaser" },
    explanation: { id: "Allah merendahkan orang yang sombong dan zalim. Kesombongan tak pernah menang di sisi-Nya.", en: "Allah lowers the arrogant and the unjust. Pride never wins with Him." },
    forKids: { id: "Ajarkan bahwa sombong membuat seseorang turun di mata Al-Khafidh.", en: "Teach that arrogance brings a person down before Al-Khafidh." },
  },
  {
    number: 23,
    slug: "ar-rafi",
    arabic: "الرَّافِعُ",
    transliteration: "Ar-Raafi'",
    meaning: { id: "Maha Meninggikan", en: "The Exalter" },
    explanation: { id: "Allah meninggikan derajat orang yang beriman dan rendah hati.", en: "Allah raises the rank of those who believe and stay humble." },
    forKids: { id: "Katakan: anak yang baik dan rendah hati akan ditinggikan Ar-Rafi'.", en: "Say: a kind, humble child is raised in honour by Ar-Rafi'." },
  },
  {
    number: 24,
    slug: "al-muizz",
    arabic: "الْمُعِزُّ",
    transliteration: "Al-Mu'izz",
    meaning: { id: "Maha Memuliakan", en: "The Honourer" },
    explanation: { id: "Allah memberi kemuliaan kepada siapa yang taat kepada-Nya.", en: "Allah grants honour to whoever obeys Him." },
    forKids: { id: "Jelaskan: kemuliaan sejati datang dari taat pada Al-Mu'izz, bukan dari harta.", en: "Explain: true honour comes from obeying Al-Mu'izz, not from wealth." },
  },
  {
    number: 25,
    slug: "al-mudzill",
    arabic: "الْمُذِلُّ",
    transliteration: "Al-Mudzill",
    meaning: { id: "Maha Menghinakan", en: "The Humiliator" },
    explanation: { id: "Allah menghinakan orang yang menyombongkan diri dan menentang kebenaran.", en: "Allah humbles those who are arrogant and oppose the truth." },
    forKids: { id: "Ingatkan: lebih baik rendah hati daripada terkena teguran Al-Mudzill.", en: "Remind: it is better to stay humble than to face the lesson of Al-Mudzill." },
  },
  {
    number: 26,
    slug: "as-sami",
    arabic: "السَّمِيعُ",
    transliteration: "As-Samii'",
    meaning: { id: "Maha Mendengar", en: "The All-Hearing" },
    explanation: { id: "Allah mendengar segala suara, bahkan doa yang kita ucapkan dalam hati.", en: "Allah hears every sound, even the prayer we whisper in our hearts." },
    forKids: { id: "Sebelum tidur, ajak anak berdoa pelan — As-Sami' pasti mendengar.", en: "Before sleep, have your child pray softly — As-Sami' surely hears." },
  },
  {
    number: 27,
    slug: "al-bashir",
    arabic: "الْبَصِيرُ",
    transliteration: "Al-Bashiir",
    meaning: { id: "Maha Melihat", en: "The All-Seeing" },
    explanation: { id: "Allah melihat segala sesuatu, sekecil apa pun, di tempat paling gelap sekalipun.", en: "Allah sees everything, however small, even in the darkest place." },
    forKids: { id: "Ingatkan dengan hangat: Al-Bashir melihat kebaikan kecil yang kita lakukan diam-diam.", en: "Warmly remind: Al-Bashir sees the small good we do quietly." },
  },
  {
    number: 28,
    slug: "al-hakam",
    arabic: "الْحَكَمُ",
    transliteration: "Al-Hakam",
    meaning: { id: "Maha Menetapkan", en: "The Judge" },
    explanation: { id: "Allah adalah Hakim yang paling adil. Keputusan-Nya tidak pernah salah.", en: "Allah is the most just Judge. His decisions are never wrong." },
    forKids: { id: "Ajarkan: kalau ada yang tidak adil di dunia, Al-Hakam pasti meluruskannya.", en: "Teach: if something is unfair in the world, Al-Hakam will surely set it right." },
  },
  {
    number: 29,
    slug: "al-adl",
    arabic: "الْعَدْلُ",
    transliteration: "Al-'Adl",
    meaning: { id: "Maha Adil", en: "The Utterly Just" },
    explanation: { id: "Allah Maha Adil. Dia memberi setiap orang haknya dengan seimbang.", en: "Allah is perfectly just. He gives everyone their right in balance." },
    forKids: { id: "Contohkan adil saat membagi: meniru sifat Al-'Adl yang membagi dengan adil.", en: "Model fairness when sharing: imitating Al-'Adl, who gives justly." },
  },
  {
    number: 30,
    slug: "al-lathif",
    arabic: "اللَّطِيفُ",
    transliteration: "Al-Lathiif",
    meaning: { id: "Maha Lembut", en: "The Subtle One" },
    explanation: { id: "Allah Maha Lembut, mengurus hal terkecil dalam hidup kita dengan penuh kasih.", en: "Allah is the Subtle One, tending the tiniest details of our lives with love." },
    forKids: { id: "Tunjuk benih yang tumbuh jadi pohon: Al-Lathif mengurus yang paling halus.", en: "Point to a seed becoming a tree: Al-Lathif manages the most delicate things." },
  },
  {
    number: 31,
    slug: "al-khabir",
    arabic: "الْخَبِيرُ",
    transliteration: "Al-Khabiir",
    meaning: { id: "Maha Mengetahui Rahasia", en: "The All-Aware" },
    explanation: { id: "Allah mengetahui rahasia dan hal yang paling tersembunyi sekalipun.", en: "Allah knows every secret and the most hidden of things." },
    forKids: { id: "Ajarkan jujur: Al-Khabir tahu yang sebenarnya, jadi tak perlu berbohong.", en: "Teach honesty: Al-Khabir knows the truth, so there's no need to lie." },
  },
  {
    number: 32,
    slug: "al-halim",
    arabic: "الْحَلِيمُ",
    transliteration: "Al-Haliim",
    meaning: { id: "Maha Penyantun", en: "The Forbearing" },
    explanation: { id: "Allah Maha Penyantun. Dia tidak terburu-buru menghukum, memberi kita waktu untuk memperbaiki diri.", en: "Allah is the Forbearing. He is not hasty to punish, giving us time to mend our ways." },
    forKids: { id: "Tiru kesabaran Al-Halim: jangan cepat marah saat orang lain salah.", en: "Imitate Al-Halim's patience: don't be quick to anger when others slip." },
  },
  {
    number: 33,
    slug: "al-azhim",
    arabic: "الْعَظِيمُ",
    transliteration: "Al-'Azhiim",
    meaning: { id: "Maha Agung", en: "The Magnificent" },
    explanation: { id: "Allah Maha Agung. Kebesaran-Nya tak mampu dibayangkan oleh akal kita.", en: "Allah is the Magnificent. His greatness is beyond what our minds can picture." },
    forKids: { id: "Pandang langit malam: bintang yang tak terhitung pun kecil bagi Al-'Azhim.", en: "Look at the night sky: even countless stars are small to Al-'Azhim." },
  },
  {
    number: 34,
    slug: "al-ghafur",
    arabic: "الْغَفُورُ",
    transliteration: "Al-Ghafuur",
    meaning: { id: "Maha Pengampun", en: "The All-Forgiving" },
    explanation: { id: "Allah Maha Pengampun yang menutupi kesalahan kita dan tidak membukanya.", en: "Allah is the All-Forgiving, who covers our mistakes and does not expose them." },
    forKids: { id: "Hibur anak yang menyesal: Al-Ghafur mengampuni dan menutupi salah kita.", en: "Comfort a regretful child: Al-Ghafur forgives and conceals our faults." },
  },
  {
    number: 35,
    slug: "asy-syakur",
    arabic: "الشَّكُورُ",
    transliteration: "Asy-Syakuur",
    meaning: { id: "Maha Pembalas Budi", en: "The Most Appreciative" },
    explanation: { id: "Allah membalas amal kecil dengan pahala yang besar dan berlipat.", en: "Allah rewards even a small good deed with a great, multiplied reward." },
    forKids: { id: "Dorong kebaikan kecil: Asy-Syakur menghargai setiap perbuatan baik.", en: "Encourage small kindness: Asy-Syakur appreciates every good deed." },
  },
  {
    number: 36,
    slug: "al-ali",
    arabic: "الْعَلِيُّ",
    transliteration: "Al-'Aliyy",
    meaning: { id: "Maha Tinggi", en: "The Most High" },
    explanation: { id: "Allah Maha Tinggi, di atas segala sesuatu dalam kedudukan dan kemuliaan.", en: "Allah is the Most High, above all things in rank and majesty." },
    forKids: { id: "Angkat tangan berdoa ke atas: kita memohon kepada Al-'Aliy yang Maha Tinggi.", en: "Raise your hands upward in dua: we ask Al-'Aliy, the Most High." },
  },
  {
    number: 37,
    slug: "al-kabir",
    arabic: "الْكَبِيرُ",
    transliteration: "Al-Kabiir",
    meaning: { id: "Maha Besar", en: "The Most Great" },
    explanation: { id: "Allah Maha Besar, lebih besar dari segala yang besar di alam semesta.", en: "Allah is the Most Great, greater than anything great in the universe." },
    forKids: { id: "Saat takbir 'Allahu Akbar', jelaskan artinya: Al-Kabir Maha Besar.", en: "During takbir 'Allahu Akbar', explain it means Al-Kabir is the Greatest." },
  },
  {
    number: 38,
    slug: "al-hafizh",
    arabic: "الْحَفِيظُ",
    transliteration: "Al-Hafiizh",
    meaning: { id: "Maha Menjaga", en: "The Preserver" },
    explanation: { id: "Allah menjaga dan memelihara segala sesuatu, termasuk amal dan diri kita.", en: "Allah preserves and guards all things, including our deeds and ourselves." },
    forKids: { id: "Bacakan ayat Kursi: ingatkan Al-Hafizh menjaga kita siang dan malam.", en: "Read Ayat al-Kursi: remind them Al-Hafizh guards us day and night." },
  },
  {
    number: 39,
    slug: "al-muqit",
    arabic: "الْمُقِيتُ",
    transliteration: "Al-Muqiit",
    meaning: { id: "Maha Pemberi Kecukupan", en: "The Sustainer" },
    explanation: { id: "Allah memberi makanan dan kekuatan kepada setiap makhluk sesuai kebutuhannya.", en: "Allah supplies food and strength to every creature according to its needs." },
    forKids: { id: "Saat anak kenyang dan kuat, ingatkan itu pemberian Al-Muqit.", en: "When your child is full and strong, note it is a gift from Al-Muqit." },
  },
  {
    number: 40,
    slug: "al-hasib",
    arabic: "الْحَسِيبُ",
    transliteration: "Al-Hasiib",
    meaning: { id: "Maha Membuat Perhitungan", en: "The Reckoner" },
    explanation: { id: "Allah menghitung setiap amal dengan teliti dan mencukupi semua kebutuhan hamba-Nya.", en: "Allah accounts for every deed precisely and is enough for all His servants' needs." },
    forKids: { id: "Ajarkan: tak ada kebaikan yang hilang, Al-Hasib menghitung semuanya.", en: "Teach: no good is ever lost; Al-Hasib counts it all." },
  },
  {
    number: 41,
    slug: "al-jalil",
    arabic: "الْجَلِيلُ",
    transliteration: "Al-Jaliil",
    meaning: { id: "Maha Luhur", en: "The Majestic" },
    explanation: { id: "Allah memiliki keluhuran dan keagungan yang sempurna.", en: "Allah possesses perfect loftiness and majesty." },
    forKids: { id: "Ajak anak mengucap 'Subhanallah' saat melihat sesuatu yang megah ciptaan Al-Jalil.", en: "Have your child say 'Subhanallah' at something grand made by Al-Jalil." },
  },
  {
    number: 42,
    slug: "al-karim",
    arabic: "الْكَرِيمُ",
    transliteration: "Al-Kariim",
    meaning: { id: "Maha Pemurah", en: "The Most Generous" },
    explanation: { id: "Allah Maha Pemurah. Dia memberi lebih dari yang kita minta dan memaafkan saat kita salah.", en: "Allah is the Most Generous. He gives more than we ask and pardons when we err." },
    forKids: { id: "Ajarkan murah hati: berbagi mainan adalah meniru kebaikan Al-Karim.", en: "Teach generosity: sharing a toy imitates the kindness of Al-Karim." },
  },
  {
    number: 43,
    slug: "ar-raqib",
    arabic: "الرَّقِيبُ",
    transliteration: "Ar-Raqiib",
    meaning: { id: "Maha Mengawasi", en: "The Watchful" },
    explanation: { id: "Allah selalu mengawasi kita, tak pernah lengah sedetik pun.", en: "Allah always watches over us, never inattentive for a moment." },
    forKids: { id: "Tanamkan kesadaran lembut: Ar-Raqib melihat, jadi mari berbuat baik walau sendiri.", en: "Plant gentle awareness: Ar-Raqib sees, so let's do good even when alone." },
  },
  {
    number: 44,
    slug: "al-mujib",
    arabic: "الْمُجِيبُ",
    transliteration: "Al-Mujiib",
    meaning: { id: "Maha Mengabulkan", en: "The Responsive" },
    explanation: { id: "Allah mengabulkan doa orang yang memohon kepada-Nya dengan tulus.", en: "Allah answers the prayer of whoever calls on Him sincerely." },
    forKids: { id: "Ajak anak berdoa untuk hal kecil — Al-Mujib senang mendengar permintaan kita.", en: "Have your child pray for small things — Al-Mujib loves to hear our requests." },
  },
  {
    number: 45,
    slug: "al-wasi",
    arabic: "الْوَاسِعُ",
    transliteration: "Al-Waasi'",
    meaning: { id: "Maha Luas", en: "The All-Encompassing" },
    explanation: { id: "Ilmu, rahmat, dan pemberian Allah sangat luas, meliputi segala sesuatu.", en: "Allah's knowledge, mercy, and giving are vast, encompassing all things." },
    forKids: { id: "Jelaskan: rahmat Al-Wasi' cukup untuk semua orang, tak pernah berkurang.", en: "Explain: Al-Wasi's mercy is enough for everyone and never decreases." },
  },
  {
    number: 46,
    slug: "al-hakim",
    arabic: "الْحَكِيمُ",
    transliteration: "Al-Hakiim",
    meaning: { id: "Maha Bijaksana", en: "The All-Wise" },
    explanation: { id: "Allah Maha Bijaksana. Setiap yang Dia lakukan dan perintahkan penuh hikmah.", en: "Allah is the All-Wise. Everything He does and commands is full of wisdom." },
    forKids: { id: "Saat sesuatu tak sesuai harapan, ingatkan ada hikmah dari Al-Hakim.", en: "When things don't go as hoped, remind them there's wisdom from Al-Hakim." },
  },
  {
    number: 47,
    slug: "al-wadud",
    arabic: "الْوَدُودُ",
    transliteration: "Al-Waduud",
    meaning: { id: "Maha Mengasihi", en: "The Most Loving" },
    explanation: { id: "Allah sangat mencintai hamba-hamba-Nya yang beriman, dan membuat mereka saling mencintai.", en: "Allah deeply loves His believing servants and places love between them." },
    forKids: { id: "Peluk anak dan katakan: cinta kita ini hadiah dari Al-Wadud.", en: "Hug your child and say: this love between us is a gift from Al-Wadud." },
  },
  {
    number: 48,
    slug: "al-majid",
    arabic: "الْمَجِيدُ",
    transliteration: "Al-Majiid",
    meaning: { id: "Maha Mulia", en: "The Most Glorious" },
    explanation: { id: "Allah Maha Mulia, memiliki kemuliaan dan kebaikan yang tak terbatas.", en: "Allah is the Most Glorious, with boundless honour and goodness." },
    forKids: { id: "Ajarkan memuliakan tamu dan orang tua, meneladani sifat Al-Majid.", en: "Teach honouring guests and elders, following the trait of Al-Majid." },
  },
  {
    number: 49,
    slug: "al-baits",
    arabic: "الْبَاعِثُ",
    transliteration: "Al-Baa'its",
    meaning: { id: "Maha Membangkitkan", en: "The Resurrector" },
    explanation: { id: "Allah akan membangkitkan semua makhluk kembali hidup di hari kiamat.", en: "Allah will resurrect all creatures to life again on the Day of Judgement." },
    forKids: { id: "Contohkan dengan biji yang 'mati' lalu tumbuh: Al-Ba'its menghidupkan kembali.", en: "Use a 'dead' seed that sprouts: Al-Ba'its brings life again." },
  },
  {
    number: 50,
    slug: "asy-syahid",
    arabic: "الشَّهِيدُ",
    transliteration: "Asy-Syahiid",
    meaning: { id: "Maha Menyaksikan", en: "The Witness" },
    explanation: { id: "Allah menyaksikan segala sesuatu, hadir di setiap tempat dan waktu.", en: "Allah witnesses everything, present in every place and time." },
    forKids: { id: "Ingatkan: Asy-Syahid menyaksikan kebaikan kita walau tak ada yang melihat.", en: "Remind: Asy-Syahid witnesses our good even when no one else sees." },
  },
  {
    number: 51,
    slug: "al-haqq",
    arabic: "الْحَقُّ",
    transliteration: "Al-Haqq",
    meaning: { id: "Maha Benar", en: "The Absolute Truth" },
    explanation: { id: "Allah adalah kebenaran yang pasti. Dia nyata dan janji-Nya selalu benar.", en: "Allah is the absolute truth. He is real and His promise is always true." },
    forKids: { id: "Ajarkan cinta kebenaran: berkata benar berarti dekat dengan Al-Haqq.", en: "Teach a love of truth: speaking truth draws us near to Al-Haqq." },
  },
  {
    number: 52,
    slug: "al-wakil",
    arabic: "الْوَكِيلُ",
    transliteration: "Al-Wakiil",
    meaning: { id: "Maha Pemelihara", en: "The Trustee" },
    explanation: { id: "Allah adalah tempat kita berserah. Cukuplah Dia sebagai penjaga urusan kita.", en: "Allah is the One we entrust our affairs to. He is enough as our Guardian." },
    forKids: { id: "Ajari ucapan tawakal: 'Hasbunallah' — cukup Al-Wakil bagi kita.", en: "Teach the words of trust: 'Hasbunallah' — Al-Wakil is enough for us." },
  },
  {
    number: 53,
    slug: "al-qawi",
    arabic: "الْقَوِيُّ",
    transliteration: "Al-Qawiyy",
    meaning: { id: "Maha Kuat", en: "The All-Strong" },
    explanation: { id: "Allah Maha Kuat. Tidak ada kekuatan yang melemahkan-Nya.", en: "Allah is the All-Strong. No force can weaken Him." },
    forKids: { id: "Saat anak merasa lemah, ingatkan ia boleh meminta kekuatan dari Al-Qawiyy.", en: "When your child feels weak, remind them they can ask Al-Qawiyy for strength." },
  },
  {
    number: 54,
    slug: "al-matin",
    arabic: "الْمَتِينُ",
    transliteration: "Al-Matiin",
    meaning: { id: "Maha Kokoh", en: "The Firm" },
    explanation: { id: "Kekuatan Allah sangat kokoh dan teguh, tak pernah goyah.", en: "Allah's strength is firm and steadfast, never shaken." },
    forKids: { id: "Jelaskan: pertolongan Al-Matin kokoh, takkan pernah mengecewakan.", en: "Explain: the help of Al-Matin is solid and will never let us down." },
  },
  {
    number: 55,
    slug: "al-wali",
    arabic: "الْوَلِيُّ",
    transliteration: "Al-Waliyy",
    meaning: { id: "Maha Melindungi", en: "The Protecting Friend" },
    explanation: { id: "Allah adalah pelindung dan penolong orang beriman dalam setiap urusan.", en: "Allah is the protecting friend and helper of believers in every affair." },
    forKids: { id: "Tenangkan anak: Al-Waliyy adalah teman terbaik yang selalu melindungi.", en: "Reassure your child: Al-Waliyy is the best friend who always protects." },
  },
  {
    number: 56,
    slug: "al-hamid",
    arabic: "الْحَمِيدُ",
    transliteration: "Al-Hamiid",
    meaning: { id: "Maha Terpuji", en: "The All-Praiseworthy" },
    explanation: { id: "Allah Maha Terpuji. Segala pujian yang baik hanya pantas untuk-Nya.", en: "Allah is the All-Praiseworthy. All good praise belongs only to Him." },
    forKids: { id: "Biasakan 'Alhamdulillah' untuk hal kecil: memuji Al-Hamid setiap hari.", en: "Make 'Alhamdulillah' a habit for small things: praising Al-Hamid daily." },
  },
  {
    number: 57,
    slug: "al-muhshi",
    arabic: "الْمُحْصِي",
    transliteration: "Al-Muhshii",
    meaning: { id: "Maha Menghitung", en: "The Accounter" },
    explanation: { id: "Allah menghitung dan mengetahui jumlah segala sesuatu, sampai butir pasir.", en: "Allah counts and knows the number of all things, down to each grain of sand." },
    forKids: { id: "Hitung bintang bersama lalu katakan: Al-Muhshi tahu jumlah persisnya.", en: "Count stars together, then say: Al-Muhshi knows their exact number." },
  },
  {
    number: 58,
    slug: "al-mubdi",
    arabic: "الْمُبْدِئُ",
    transliteration: "Al-Mubdi'",
    meaning: { id: "Maha Memulai", en: "The Originator" },
    explanation: { id: "Allah yang memulai penciptaan segala sesuatu untuk pertama kalinya.", en: "Allah is the One who began the creation of all things for the first time." },
    forKids: { id: "Tanya: siapa yang pertama membuat bunga ada? Al-Mubdi'.", en: "Ask: who first made flowers exist? Al-Mubdi'." },
  },
  {
    number: 59,
    slug: "al-muid",
    arabic: "الْمُعِيدُ",
    transliteration: "Al-Mu'iid",
    meaning: { id: "Maha Mengembalikan", en: "The Restorer" },
    explanation: { id: "Allah mengembalikan dan mengulang penciptaan, lalu membangkitkan kita kembali.", en: "Allah restores and repeats creation, then brings us back to life." },
    forKids: { id: "Tunjuk musim yang berulang: Al-Mu'id mengulang segalanya dengan teratur.", en: "Point to the returning seasons: Al-Mu'id repeats all things in order." },
  },
  {
    number: 60,
    slug: "al-muhyi",
    arabic: "الْمُحْيِي",
    transliteration: "Al-Muhyii",
    meaning: { id: "Maha Menghidupkan", en: "The Giver of Life" },
    explanation: { id: "Allah yang memberi kehidupan kepada segala sesuatu yang hidup.", en: "Allah is the One who gives life to all that lives." },
    forKids: { id: "Lihat bayi atau anak kucing: Al-Muhyi yang meniupkan kehidupan.", en: "Look at a baby or a kitten: Al-Muhyi gave them life." },
  },
  {
    number: 61,
    slug: "al-mumit",
    arabic: "الْمُمِيتُ",
    transliteration: "Al-Mumiit",
    meaning: { id: "Maha Mematikan", en: "The Bringer of Death" },
    explanation: { id: "Allah yang menentukan datangnya kematian bagi setiap makhluk pada waktunya.", en: "Allah decrees death for every creature at its appointed time." },
    forKids: { id: "Jelaskan dengan lembut bahwa hidup dan mati ada di tangan Al-Mumit.", en: "Gently explain that life and death are in the hands of Al-Mumit." },
  },
  {
    number: 62,
    slug: "al-hayy",
    arabic: "الْحَيُّ",
    transliteration: "Al-Hayy",
    meaning: { id: "Maha Hidup", en: "The Ever-Living" },
    explanation: { id: "Allah Maha Hidup, selalu ada, tak pernah tidur atau mati.", en: "Allah is the Ever-Living, always present, never sleeping or dying." },
    forKids: { id: "Bandingkan dengan kita yang lelah dan tidur: Al-Hayy tak pernah lelah.", en: "Compare to us who tire and sleep: Al-Hayy never tires." },
  },
  {
    number: 63,
    slug: "al-qayyum",
    arabic: "الْقَيُّومُ",
    transliteration: "Al-Qayyuum",
    meaning: { id: "Maha Mandiri", en: "The Self-Subsisting" },
    explanation: { id: "Allah berdiri sendiri dan mengurus seluruh alam tanpa bantuan siapa pun.", en: "Allah is self-subsisting and sustains all creation without anyone's help." },
    forKids: { id: "Jelaskan: bintang dan langit tetap teratur karena dijaga Al-Qayyum.", en: "Explain: the stars and skies stay in order because Al-Qayyum sustains them." },
  },
  {
    number: 64,
    slug: "al-wajid",
    arabic: "الْوَاجِدُ",
    transliteration: "Al-Waajid",
    meaning: { id: "Maha Menemukan", en: "The Perceiver" },
    explanation: { id: "Allah menemukan dan memiliki segala yang Dia kehendaki. Tidak ada yang kurang bagi-Nya.", en: "Allah finds and has whatever He wills. Nothing is lacking for Him." },
    forKids: { id: "Ajarkan: Al-Wajid tak pernah kehabisan apa pun untuk menolong kita.", en: "Teach: Al-Wajid never runs short of anything to help us." },
  },
  {
    number: 65,
    slug: "al-maajid",
    arabic: "الْمَاجِدُ",
    transliteration: "Al-Maajid",
    meaning: { id: "Maha Mulia", en: "The Illustrious" },
    explanation: { id: "Allah Maha Mulia, agung dalam kebaikan dan kedermawanan-Nya.", en: "Allah is the Illustrious, grand in His goodness and generosity." },
    forKids: { id: "Ceritakan kemurahan Allah yang tak terbatas — itulah Al-Majid.", en: "Tell of Allah's limitless generosity — that is Al-Majid." },
  },
  {
    number: 66,
    slug: "al-wahid",
    arabic: "الْوَاحِدُ",
    transliteration: "Al-Waahid",
    meaning: { id: "Maha Esa", en: "The One" },
    explanation: { id: "Allah Maha Esa, satu-satunya Tuhan tanpa sekutu.", en: "Allah is the One, the only God with no partner." },
    forKids: { id: "Tunjukkan satu jari: hanya ada satu Tuhan, Al-Wahid.", en: "Hold up one finger: there is only one God, Al-Wahid." },
  },
  {
    number: 67,
    slug: "al-ahad",
    arabic: "الْأَحَدُ",
    transliteration: "Al-Ahad",
    meaning: { id: "Maha Tunggal", en: "The Indivisible" },
    explanation: { id: "Allah Maha Tunggal, tidak terbagi dan tidak ada yang menyerupai-Nya.", en: "Allah is the Indivisible, undivided and unlike anything else." },
    forKids: { id: "Bacakan surat Al-Ikhlas: 'Qul huwallahu ahad' — Allah Al-Ahad.", en: "Read Surah al-Ikhlas: 'Qul huwallahu ahad' — Allah is Al-Ahad." },
  },
  {
    number: 68,
    slug: "as-samad",
    arabic: "الصَّمَدُ",
    transliteration: "As-Shamad",
    meaning: { id: "Maha Tempat Bergantung", en: "The Eternal Refuge" },
    explanation: { id: "Allah tempat bergantung segala makhluk, sedangkan Dia tidak bergantung pada siapa pun.", en: "Allah is the One all creatures depend on, while He depends on no one." },
    forKids: { id: "Saat anak butuh sesuatu, arahkan ke As-Samad, tempat meminta segalanya.", en: "When your child needs something, point them to As-Samad, whom we ask for all." },
  },
  {
    number: 69,
    slug: "al-qadir",
    arabic: "الْقَادِرُ",
    transliteration: "Al-Qaadir",
    meaning: { id: "Maha Kuasa", en: "The All-Powerful" },
    explanation: { id: "Allah Maha Kuasa atas segala sesuatu. Apa yang Dia kehendaki pasti terjadi.", en: "Allah has power over all things. What He wills surely happens." },
    forKids: { id: "Saat sesuatu terasa mustahil, ingatkan tidak ada yang sulit bagi Al-Qadir.", en: "When something feels impossible, remind them nothing is hard for Al-Qadir." },
  },
  {
    number: 70,
    slug: "al-muqtadir",
    arabic: "الْمُقْتَدِرُ",
    transliteration: "Al-Muqtadir",
    meaning: { id: "Maha Berkuasa", en: "The Determiner" },
    explanation: { id: "Allah sangat berkuasa, menentukan segala sesuatu dengan kekuatan penuh.", en: "Allah is fully capable, determining all matters with complete power." },
    forKids: { id: "Tunjuk laut atau gunung: semua tunduk pada Al-Muqtadir.", en: "Point to the sea or a mountain: all of it bows to Al-Muqtadir." },
  },
  {
    number: 71,
    slug: "al-muqaddim",
    arabic: "الْمُقَدِّمُ",
    transliteration: "Al-Muqaddim",
    meaning: { id: "Maha Mendahulukan", en: "The Expediter" },
    explanation: { id: "Allah mendahulukan dan mengutamakan apa serta siapa yang Dia kehendaki.", en: "Allah brings forward and gives precedence to what and whom He wills." },
    forKids: { id: "Ajarkan: Al-Muqaddim mendahulukan orang yang bersegera dalam kebaikan.", en: "Teach: Al-Muqaddim favours those who hurry to do good." },
  },
  {
    number: 72,
    slug: "al-muakhkhir",
    arabic: "الْمُؤَخِّرُ",
    transliteration: "Al-Mu'akhkhir",
    meaning: { id: "Maha Mengakhirkan", en: "The Delayer" },
    explanation: { id: "Allah menunda sesuatu sesuai hikmah-Nya. Penundaan-Nya bukan berarti melupakan.", en: "Allah delays matters by His wisdom. His delay never means He forgets." },
    forKids: { id: "Ajarkan sabar menunggu: kadang Al-Mu'akhkhir menunda untuk kebaikan kita.", en: "Teach patience in waiting: sometimes Al-Mu'akhkhir delays for our good." },
  },
  {
    number: 73,
    slug: "al-awwal",
    arabic: "الْأَوَّلُ",
    transliteration: "Al-Awwal",
    meaning: { id: "Maha Awal", en: "The First" },
    explanation: { id: "Allah Yang Pertama, ada sebelum segala sesuatu tanpa permulaan.", en: "Allah is the First, existing before all things with no beginning." },
    forKids: { id: "Tanya: apa yang ada sebelum bumi, bulan, dan bintang? Al-Awwal.", en: "Ask: what existed before the earth, moon, and stars? Al-Awwal." },
  },
  {
    number: 74,
    slug: "al-akhir",
    arabic: "الْآخِرُ",
    transliteration: "Al-Aakhir",
    meaning: { id: "Maha Akhir", en: "The Last" },
    explanation: { id: "Allah Yang Terakhir, tetap ada setelah segala sesuatu berakhir.", en: "Allah is the Last, remaining after all things come to an end." },
    forKids: { id: "Jelaskan: segala sesuatu ada masanya, tetapi Al-Akhir tetap selamanya.", en: "Explain: everything has its time, but Al-Akhir remains forever." },
  },
  {
    number: 75,
    slug: "azh-zhahir",
    arabic: "الظَّاهِرُ",
    transliteration: "Azh-Zhaahir",
    meaning: { id: "Maha Nyata", en: "The Manifest" },
    explanation: { id: "Allah Maha Nyata; tanda-tanda kebesaran-Nya tampak di mana-mana.", en: "Allah is the Manifest; signs of His greatness appear everywhere." },
    forKids: { id: "Ajak anak menyebut tanda Azh-Zhahir: matahari, pohon, hujan, dan dirinya.", en: "Have your child name signs of Azh-Zhahir: the sun, trees, rain, and themselves." },
  },
  {
    number: 76,
    slug: "al-bathin",
    arabic: "الْبَاطِنُ",
    transliteration: "Al-Baathin",
    meaning: { id: "Maha Tersembunyi", en: "The Hidden" },
    explanation: { id: "Allah Maha Tersembunyi; Dia lebih dekat dari yang kita kira, walau tak terlihat mata.", en: "Allah is the Hidden; He is closer than we think, though unseen by the eye." },
    forKids: { id: "Jelaskan: kita tak melihat Al-Bathin, tetapi Dia selalu dekat dengan kita.", en: "Explain: we don't see Al-Bathin, yet He is always near to us." },
  },
  {
    number: 77,
    slug: "al-walii",
    arabic: "الْوَالِي",
    transliteration: "Al-Waalii",
    meaning: { id: "Maha Menguasai", en: "The Governor" },
    explanation: { id: "Allah menguasai dan mengatur segala urusan alam semesta.", en: "Allah governs and manages all the affairs of the universe." },
    forKids: { id: "Tunjuk keteraturan siang-malam: Al-Wali yang mengaturnya.", en: "Point to the order of day and night: Al-Wali arranges it." },
  },
  {
    number: 78,
    slug: "al-mutaali",
    arabic: "الْمُتَعَالِي",
    transliteration: "Al-Muta'aalii",
    meaning: { id: "Maha Tinggi", en: "The Most Exalted" },
    explanation: { id: "Allah Maha Tinggi, jauh di atas segala kekurangan yang dibayangkan makhluk.", en: "Allah is the Most Exalted, far above any flaw a creature could imagine." },
    forKids: { id: "Ajarkan mengagungkan Allah: Al-Muta'ali lebih tinggi dari segalanya.", en: "Teach reverence for Allah: Al-Muta'ali is higher than all." },
  },
  {
    number: 79,
    slug: "al-barr",
    arabic: "الْبَرُّ",
    transliteration: "Al-Barr",
    meaning: { id: "Maha Penderma", en: "The Source of Goodness" },
    explanation: { id: "Allah Maha Baik dan banyak memberi kebaikan kepada hamba-Nya.", en: "Allah is the Source of Goodness, abundant in kindness to His servants." },
    forKids: { id: "Hitung kebaikan hari ini: semua adalah curahan dari Al-Barr.", en: "Count today's kindnesses: all of them pour from Al-Barr." },
  },
  {
    number: 80,
    slug: "at-tawwab",
    arabic: "التَّوَّابُ",
    transliteration: "At-Tawwaab",
    meaning: { id: "Maha Penerima Tobat", en: "The Acceptor of Repentance" },
    explanation: { id: "Allah selalu menerima tobat hamba yang kembali kepada-Nya, berapa kali pun.", en: "Allah always accepts the repentance of a servant who turns back, however often." },
    forKids: { id: "Ajari anak meminta maaf kepada Allah; At-Tawwab senang menerima tobat.", en: "Teach your child to seek Allah's pardon; At-Tawwab loves to accept repentance." },
  },
  {
    number: 81,
    slug: "al-muntaqim",
    arabic: "الْمُنْتَقِمُ",
    transliteration: "Al-Muntaqim",
    meaning: { id: "Maha Pemberi Balasan", en: "The Avenger" },
    explanation: { id: "Allah memberi balasan yang adil kepada orang zalim yang tidak mau berhenti.", en: "Allah gives just recompense to wrongdoers who refuse to stop." },
    forKids: { id: "Ajarkan: kezaliman pasti dibalas adil oleh Al-Muntaqim, jadi jangan menzalimi.", en: "Teach: wrongdoing is justly answered by Al-Muntaqim, so never wrong others." },
  },
  {
    number: 82,
    slug: "al-afu",
    arabic: "الْعَفُوُّ",
    transliteration: "Al-'Afuww",
    meaning: { id: "Maha Pemaaf", en: "The Pardoner" },
    explanation: { id: "Allah menghapus kesalahan kita sampai seakan tak pernah terjadi.", en: "Allah erases our sins until it is as if they never happened." },
    forKids: { id: "Ajari doa Lailatul Qadar: 'Allahumma innaka 'Afuwwun tuhibbul 'afwa fa'fu 'anni'.", en: "Teach the Laylatul Qadr dua: 'O Allah, You are the Pardoner who loves to pardon, so pardon me.'" },
  },
  {
    number: 83,
    slug: "ar-rauf",
    arabic: "الرَّؤُوفُ",
    transliteration: "Ar-Ra'uuf",
    meaning: { id: "Maha Pengasih", en: "The Most Kind" },
    explanation: { id: "Allah sangat lembut dan penyayang, tidak membebani kita di luar kemampuan.", en: "Allah is deeply kind and gentle, never burdening us beyond what we can bear." },
    forKids: { id: "Tenangkan anak yang lelah: Ar-Ra'uf tidak memberi beban terlalu berat.", en: "Reassure a tired child: Ar-Ra'uf never gives a burden too heavy." },
  },
  {
    number: 84,
    slug: "malikul-mulk",
    arabic: "مَالِكُ الْمُلْكِ",
    transliteration: "Maalikul-Mulk",
    meaning: { id: "Maha Penguasa Kerajaan", en: "Master of the Kingdom" },
    explanation: { id: "Allah pemilik dan penguasa seluruh kerajaan; Dia memberi kekuasaan kepada siapa yang Dia mau.", en: "Allah owns and rules all dominion; He grants authority to whom He wills." },
    forKids: { id: "Jelaskan: pemimpin di dunia hanya dipinjami kuasa oleh Malikul-Mulk.", en: "Explain: leaders are only lent their power by Malikul-Mulk." },
  },
  {
    number: 85,
    slug: "dzul-jalali-wal-ikram",
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Dzul-Jalaali wal-Ikraam",
    meaning: { id: "Maha Pemilik Keagungan dan Kemuliaan", en: "Lord of Majesty and Honour" },
    explanation: { id: "Allah pemilik keagungan yang membuat kita kagum dan kemuliaan yang mencurahkan kebaikan.", en: "Allah possesses majesty that awes us and honour that pours out goodness." },
    forKids: { id: "Ajak mengucap nama ini saat berdoa — penuh keagungan Dzul-Jalali wal-Ikram.", en: "Use this name in dua — full of the majesty of Dzul-Jalali wal-Ikram." },
  },
  {
    number: 86,
    slug: "al-muqsith",
    arabic: "الْمُقْسِطُ",
    transliteration: "Al-Muqsith",
    meaning: { id: "Maha Adil", en: "The Equitable" },
    explanation: { id: "Allah Maha Adil yang menegakkan keadilan dengan penuh kasih bagi semua.", en: "Allah is the Equitable, establishing justice with care for all." },
    forKids: { id: "Ajarkan berlaku adil pada teman, meneladani Al-Muqsith.", en: "Teach being fair to friends, following Al-Muqsith." },
  },
  {
    number: 87,
    slug: "al-jami",
    arabic: "الْجَامِعُ",
    transliteration: "Al-Jaami'",
    meaning: { id: "Maha Mengumpulkan", en: "The Gatherer" },
    explanation: { id: "Allah mengumpulkan yang terpisah; kelak Dia mengumpulkan semua manusia di hari kiamat.", en: "Allah gathers what is scattered; one day He will gather all people for Judgement." },
    forKids: { id: "Saat keluarga berkumpul, ingatkan ini nikmat dari Al-Jami'.", en: "When family gathers, note it is a blessing from Al-Jami'." },
  },
  {
    number: 88,
    slug: "al-ghani",
    arabic: "الْغَنِيُّ",
    transliteration: "Al-Ghaniyy",
    meaning: { id: "Maha Kaya", en: "The Self-Sufficient" },
    explanation: { id: "Allah Maha Kaya, tidak butuh apa pun, sedangkan semua makhluk butuh kepada-Nya.", en: "Allah is the Self-Sufficient, needing nothing, while all creatures need Him." },
    forKids: { id: "Ajarkan: kita selalu butuh Al-Ghaniyy, tetapi Dia tidak butuh kita.", en: "Teach: we always need Al-Ghaniyy, yet He needs nothing from us." },
  },
  {
    number: 89,
    slug: "al-mughni",
    arabic: "الْمُغْنِي",
    transliteration: "Al-Mughnii",
    meaning: { id: "Maha Pemberi Kekayaan", en: "The Enricher" },
    explanation: { id: "Allah mencukupkan dan memberi kekayaan kepada siapa yang Dia kehendaki.", en: "Allah enriches and grants sufficiency to whom He wills." },
    forKids: { id: "Ajarkan merasa cukup: Al-Mughni yang memberi kita semua kebutuhan.", en: "Teach contentment: Al-Mughni provides all that we need." },
  },
  {
    number: 90,
    slug: "al-mani",
    arabic: "الْمَانِعُ",
    transliteration: "Al-Maani'",
    meaning: { id: "Maha Mencegah", en: "The Preventer" },
    explanation: { id: "Allah mencegah dan menahan apa yang membahayakan kita demi kebaikan kita.", en: "Allah prevents and holds back what would harm us, for our own good." },
    forKids: { id: "Jelaskan: kadang Al-Mani' menahan keinginan kita untuk menjaga kita.", en: "Explain: sometimes Al-Mani' withholds a wish to protect us." },
  },
  {
    number: 91,
    slug: "adh-dharr",
    arabic: "الضَّارُّ",
    transliteration: "Adh-Dhaarr",
    meaning: { id: "Maha Pemberi Bahaya", en: "The Distresser" },
    explanation: { id: "Tidak ada bahaya yang menimpa kecuali dengan izin Allah, dan selalu ada hikmahnya.", en: "No harm befalls anyone except by Allah's permission, and always with wisdom." },
    forKids: { id: "Ajarkan berlindung kepada Allah dari segala bahaya, sebab semua di tangan-Nya.", en: "Teach seeking refuge in Allah from all harm, since everything is in His hands." },
  },
  {
    number: 92,
    slug: "an-nafi",
    arabic: "النَّافِعُ",
    transliteration: "An-Naafi'",
    meaning: { id: "Maha Pemberi Manfaat", en: "The Benefactor" },
    explanation: { id: "Semua manfaat dan kebaikan datang dari Allah semata.", en: "Every benefit and good comes from Allah alone." },
    forKids: { id: "Saat sesuatu menolong kita, ingatkan manfaat itu dari An-Nafi'.", en: "When something helps us, note the benefit comes from An-Nafi'." },
  },
  {
    number: 93,
    slug: "an-nur",
    arabic: "النُّورُ",
    transliteration: "An-Nuur",
    meaning: { id: "Maha Bercahaya", en: "The Light" },
    explanation: { id: "Allah adalah cahaya langit dan bumi yang menerangi hati menuju kebenaran.", en: "Allah is the light of the heavens and earth, lighting hearts toward truth." },
    forKids: { id: "Saat menyalakan lampu, ingatkan An-Nur menerangi hati kita dengan iman.", en: "When you switch on a light, note An-Nur lights our hearts with faith." },
  },
  {
    number: 94,
    slug: "al-hadi",
    arabic: "الْهَادِي",
    transliteration: "Al-Haadii",
    meaning: { id: "Maha Pemberi Petunjuk", en: "The Guide" },
    explanation: { id: "Allah memberi petunjuk kepada hamba-Nya menuju jalan yang benar.", en: "Allah guides His servants to the straight path." },
    forKids: { id: "Ajari doa minta petunjuk setiap salat: 'Ihdinash-shiratal-mustaqim'.", en: "Teach the dua for guidance in every prayer: 'Ihdinas-siratal-mustaqim'." },
  },
  {
    number: 95,
    slug: "al-badi",
    arabic: "الْبَدِيعُ",
    transliteration: "Al-Badii'",
    meaning: { id: "Maha Pencipta Tiada Bandingan", en: "The Incomparable Originator" },
    explanation: { id: "Allah menciptakan hal-hal yang menakjubkan tanpa ada contoh sebelumnya.", en: "Allah creates wondrous things with no prior example." },
    forKids: { id: "Tunjuk sarang lebah atau pelangi: karya unik dari Al-Badi'.", en: "Point to a honeycomb or a rainbow: a unique work of Al-Badi'." },
  },
  {
    number: 96,
    slug: "al-baqi",
    arabic: "الْبَاقِي",
    transliteration: "Al-Baaqii",
    meaning: { id: "Maha Kekal", en: "The Everlasting" },
    explanation: { id: "Allah Maha Kekal, tetap ada selamanya saat segala sesuatu binasa.", en: "Allah is the Everlasting, remaining forever when all else perishes." },
    forKids: { id: "Jelaskan: mainan bisa rusak, tetapi Al-Baqi tetap ada selamanya.", en: "Explain: toys can break, but Al-Baqi remains forever." },
  },
  {
    number: 97,
    slug: "al-warits",
    arabic: "الْوَارِثُ",
    transliteration: "Al-Waarits",
    meaning: { id: "Maha Pewaris", en: "The Inheritor" },
    explanation: { id: "Allah pemilik abadi segala sesuatu setelah semua makhluk tiada.", en: "Allah is the eternal owner of all things after every creature is gone." },
    forKids: { id: "Ajarkan: semua yang kita punya akan kembali kepada Al-Warits.", en: "Teach: everything we have will return to Al-Warits." },
  },
  {
    number: 98,
    slug: "ar-rasyid",
    arabic: "الرَّشِيدُ",
    transliteration: "Ar-Rasyiid",
    meaning: { id: "Maha Pembimbing", en: "The Guide to the Right Path" },
    explanation: { id: "Allah membimbing segala urusan menuju kebaikan dengan kebijaksanaan sempurna.", en: "Allah guides all affairs toward good with perfect wisdom." },
    forKids: { id: "Saat membuat pilihan, ajak minta bimbingan kepada Ar-Rasyid.", en: "When making a choice, ask for the guidance of Ar-Rasyid." },
  },
  {
    number: 99,
    slug: "as-sabur",
    arabic: "الصَّبُورُ",
    transliteration: "As-Shabuur",
    meaning: { id: "Maha Sabar", en: "The Patient One" },
    explanation: { id: "Allah Maha Sabar; Dia tidak tergesa-gesa dan memberi kesempatan kepada hamba-Nya.", en: "Allah is the Patient One; He is never hasty and gives His servants time." },
    forKids: { id: "Teladani kesabaran As-Sabur: bersabar saat menunggu dan saat kecewa.", en: "Model the patience of As-Sabur: stay patient when waiting and when let down." },
  },
];

export function getAllAsmaulHusna(): AsmaulHusna[] {
  return asmaulHusnaList;
}

export function getAsmaulHusnaBySlug(slug: string): AsmaulHusna | undefined {
  return asmaulHusnaList.find((n) => n.slug === slug);
}

export function getAsmaulHusnaByNumber(num: number): AsmaulHusna | undefined {
  return asmaulHusnaList.find((n) => n.number === num);
}

export function getAsmaulHusnaSlugs(): string[] {
  return asmaulHusnaList.map((n) => n.slug);
}
